name: Bug Report
description: Something is broken
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: What's broken?
      placeholder: Short description
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. See ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior (with error output if any)
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: "OS, Node/Python version, relevant config"
